language: python
python:
  - "3.4"
  - "3.5"
sudo: false

before_install: pip install codecov
after_success:  codecov

install:
  - python install_resources.py omssa_2_1_9
  - pip install -r requirements.txt

script: nosetests --with-coverage
